package be.plutus.core.model;

import be.plutus.common.DateService;
import be.plutus.common.IdentifierService;

public enum CredentialsIdentity{

    IPHONE6_IOS10_2(
            "iOS",
            "iPhone7,2",
            "Mozilla/5.0 (iPhone; CPU iPhone OS 10_2 like Mac OS X) AppleWebKit/602.3.12 (KHTML, like Gecko) Mobile/14C92"
    ),
    IPHONESE_IOS10_0_1(
            "iOS",
            "iPhone8,4",
            "Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_1 like Mac OS X) AppleWebKit/602.1.32 (KHTML, like Gecko) Mobile/14A403"
    ),
    IPHONE6PLUS_IOS9_3_5(
            "iOS",
            "iPhone7,1",
            "Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_5 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13G36"
    ),
    ONEPLUS3T_ANDROID7_1_1(
            "Android",
            "ONEPLUS A3003",
            "Mozilla/5.0 (Linux; Android 7.1.1; ONEPLUS A3003 Build/NMF26F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Crosswalk/15.44.384.12 Mobile Safari/537.36"
    );

    public String os;
    private String deviceModel;
    private String userAgent;

    CredentialsIdentity( String os, String deviceModel, String userAgent ){
        this.os = os;
        this.deviceModel = deviceModel;
        this.userAgent = userAgent;
    }

    public String toUUID(){
        return os.equals( "Android" ) ? IdentifierService.generateAndroidID() : IdentifierService.generateUUID();
    }

    public String toDeviceModel(){
        return this.deviceModel;
    }

    public String toUserAgent(){
        return userAgent + ( os.equals( "Android" ) ? "" : generateSuffix() );
    }

    private String generateSuffix(){
        // This is not exact science. I have no idea how the number between parentheses at the end of the user agent
        // is generated by the MyInepro app.
        return " (" + ( DateService.now().toEpochSecond() * 2.86 ) + ")";
    }
}
